package br.com.todeschini.domain.business.mdf.usedpaintingborderbackground.api;

public interface UsedPaintingBorderBackgroundService extends FindUsedPaintingBorderBackground, InsertUsedPaintingBorderBackground, UpdateUsedPaintingBorderBackground, DeleteUsedPaintingBorderBackground, InactivateUsedPaintingBorderBackground,
        FindAllActiveUsedPaintingBorderBackgroundAndCurrentOne {
}
