
    create table public.trash (
       id bigint generated by default as identity,
        date timestamp not null,
        entity_id jsonb not null,
        referenced_table varchar(200) not null,
        status varchar(255) not null,
        table_name varchar(50) not null,
        username varchar(50) not null,
        primary key (id)
    );

    alter table public.trash 
       add constraint UK_pd8f4g88vutlds0u4u7t4oyhb unique (entity_id);

    create table tb_aluminium_son_son (
       aluminium_son_id bigint not null,
        son_id bigint not null
    );

    create table tb_aluminium_type (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        less_quantity double precision,
        name varchar(255),
        primary key (id)
    );

    create table tb_back (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        measure1 integer,
        measure2 integer,
        suffix integer,
        thickness double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_color (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        name varchar(255),
        primary key (code)
    );

    create table tb_corner_bracket (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_edge_banding (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        height integer,
        thickness integer,
        color_id bigint,
        primary key (code)
    );

    create table tb_father_attachment (
       father_id bigint not null,
        attachment_id bigint not null,
        primary key (father_id, attachment_id)
    );

    create table tb_ghost (
       code varchar(255) not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        measure1 integer,
        measure2 integer,
        measure3 integer,
        suffix varchar(255),
        primary key (code)
    );

    create table tb_glue (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        grammage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_guide (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        final_date date,
        implementation date,
        primary key (id)
    );

    create table tb_guide_machine (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        machine_time double precision,
        man_time double precision,
        measurement_unit varchar(255),
        guide_id bigint not null,
        machine_id bigint not null,
        primary key (id)
    );

    create table tb_item (
       dtype varchar(31) not null,
        code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        measure1 integer,
        measure2 integer,
        measure3 integer,
        measurement_unit varchar(255),
        faces integer,
        high_shine boolean,
        satin boolean,
        satin_glass boolean,
        special boolean,
        suffix integer,
        color_id bigint,
        father_id bigint,
        guide_id bigint,
        aluminium_type_id bigint,
        used_drawer_pull_id bigint,
        used_glass_id bigint,
        back_id bigint,
        ghost_id varchar(255),
        primary key (code)
    );

    create table tb_machine (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        name varchar(255),
        machine_group_id bigint,
        formula character varying(255)[],
        primary key (id)
    );

    create table tb_machine_group (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_material (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_nonwoven_fabric (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_painting (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        painting_type_id bigint,
        primary key (code)
    );

    create table tb_painting_border_background (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_painting_type (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        primary key (id)
    );

    create table tb_plastic (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        grammage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_polyester (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_polyethylene (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        color_id bigint,
        primary key (code)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_sheet (
       code bigint not null,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        description varchar(255),
        family varchar(255),
        implementation date,
        lost_percentage double precision,
        faces integer,
        thickness double precision,
        color_id bigint,
        material_id bigint,
        primary key (code)
    );

    create table tb_used_back_sheet (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        back_id bigint not null,
        sheet_id bigint not null,
        primary key (id)
    );

    create table tb_used_corner_bracket (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        quantity integer,
        corner_bracket_id bigint not null,
        ghost_id varchar(255) not null,
        primary key (id)
    );

    create table tb_used_drawer_pull (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        measurement_unit varchar(255),
        quantity double precision,
        aluminium_son_id bigint not null,
        drawer_pull_id bigint not null,
        primary key (id)
    );

    create table tb_used_edge_banding (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        edge_length integer,
        edge_width integer,
        edge_banding_id bigint not null,
        son_id bigint not null,
        primary key (id)
    );

    create table tb_used_glass (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        measurement_unit varchar(255),
        quantity double precision,
        aluminium_son_id bigint not null,
        glass_id bigint not null,
        primary key (id)
    );

    create table tb_used_glue (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        glue_id bigint not null,
        son_id bigint not null,
        primary key (id)
    );

    create table tb_used_molding (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        measurement_unit varchar(255),
        quantity double precision,
        aluminium_son_id bigint not null,
        molding_id bigint not null,
        primary key (id)
    );

    create table tb_used_nonwoven_fabric (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        one_face boolean,
        ghost_id varchar(255) not null,
        nonwoven_fabric_id bigint not null,
        primary key (id)
    );

    create table tb_used_painting (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        painting_id bigint not null,
        painting_son_id bigint not null,
        primary key (id)
    );

    create table tb_used_painting_border_background (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        painting_border_background_id bigint not null,
        painting_son_id bigint not null,
        primary key (id)
    );

    create table tb_used_plastic (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        additional double precision,
        upper boolean,
        width integer,
        ghost_id varchar(255) not null,
        plastic_id bigint not null,
        primary key (id)
    );

    create table tb_used_polyester (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        painting_son_id bigint not null,
        polyester_id bigint not null,
        primary key (id)
    );

    create table tb_used_polyethylene (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        ghost_id varchar(255) not null,
        polyethylene_id bigint not null,
        primary key (id)
    );

    create table tb_used_screw (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        measurement_unit varchar(255),
        quantity double precision,
        aluminium_son_id bigint not null,
        screw_id bigint not null,
        primary key (id)
    );

    create table tb_used_sheet (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        gross_quantity double precision,
        measurement_unit varchar(255),
        net_quantity double precision,
        sheet_id bigint not null,
        son_id bigint not null,
        primary key (id)
    );

    create table tb_used_try_square (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        measurement_unit varchar(255),
        quantity double precision,
        aluminium_son_id bigint not null,
        try_square_id bigint not null,
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        created_by varchar(50),
        creation_date timestamp,
        last_modified_by varchar(50),
        last_modified_date timestamp,
        status varchar(255),
        email varchar(255),
        img_url TEXT,
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_user 
       add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

    alter table tb_aluminium_son_son 
       add constraint FKjp8h708p9uk4h780rgra0f2nw 
       foreign key (son_id) 
       references tb_item;

    alter table tb_aluminium_son_son 
       add constraint FK8xm6642hr4ai81krdjqiraabo 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_back 
       add constraint FKe19skxvw7nlyla5d13bar85c8 
       foreign key (color_id) 
       references tb_color;

    alter table tb_corner_bracket 
       add constraint FKux6go641clushvpy3f1pohbu 
       foreign key (color_id) 
       references tb_color;

    alter table tb_edge_banding 
       add constraint FKntofo0lwn138wrtwsb8di9l55 
       foreign key (color_id) 
       references tb_color;

    alter table tb_father_attachment 
       add constraint FKcfn471qgxpvycdufukrm9dk0x 
       foreign key (attachment_id) 
       references tb_item;

    alter table tb_father_attachment 
       add constraint FKd3kcdtm4j7iknoapdbtskmvof 
       foreign key (father_id) 
       references tb_item;

    alter table tb_glue 
       add constraint FKc2mx76uxlqlfjfvkg2dwkm340 
       foreign key (color_id) 
       references tb_color;

    alter table tb_guide_machine 
       add constraint FKl3w4g7ivjfxe40d70ho5axnib 
       foreign key (guide_id) 
       references tb_guide;

    alter table tb_guide_machine 
       add constraint FKrop2lkx346c91roearmxk3kk4 
       foreign key (machine_id) 
       references tb_machine;

    alter table tb_item 
       add constraint FKbuqxoap1hvug02bfpusrcc571 
       foreign key (color_id) 
       references tb_color;

    alter table tb_item 
       add constraint FKnavhcl6swcomn8mktdqq95fxv 
       foreign key (father_id) 
       references tb_item;

    alter table tb_item 
       add constraint FKak3kmg0b5c3hb9437v668envr 
       foreign key (guide_id) 
       references tb_guide;

    alter table tb_item 
       add constraint FK45vxwyy2sftfgpo092cqssvy3 
       foreign key (aluminium_type_id) 
       references tb_aluminium_type;

    alter table tb_item 
       add constraint FKhjrobnwiv0oe6vqm6rmwy7s9o 
       foreign key (used_drawer_pull_id) 
       references tb_used_drawer_pull;

    alter table tb_item 
       add constraint FK1a4t67ooxdhpxyfd9trwrrswy 
       foreign key (used_glass_id) 
       references tb_used_glass;

    alter table tb_item 
       add constraint FKsy58m5vhuwkcvohofsat00m05 
       foreign key (back_id) 
       references tb_back;

    alter table tb_item 
       add constraint FKlhijopm88yg4wrxr96m7l6m7j 
       foreign key (ghost_id) 
       references tb_ghost;

    alter table tb_machine 
       add constraint FKdpghxit3klyyg26sqw4crgo4i 
       foreign key (machine_group_id) 
       references tb_machine_group;

    alter table tb_nonwoven_fabric 
       add constraint FKqhdeoj6u9knif0j2qhmjqkemy 
       foreign key (color_id) 
       references tb_color;

    alter table tb_painting 
       add constraint FKjetgmdlnd303pl7ieiauvuoyh 
       foreign key (color_id) 
       references tb_color;

    alter table tb_painting 
       add constraint FKjn98youbnnyg0bw23kx6w8li1 
       foreign key (painting_type_id) 
       references tb_painting_type;

    alter table tb_painting_border_background 
       add constraint FK1bme18ld5rh41w3cf5fv3mct4 
       foreign key (color_id) 
       references tb_color;

    alter table tb_plastic 
       add constraint FKeop62gc54ek40tsqwjq3ys581 
       foreign key (color_id) 
       references tb_color;

    alter table tb_polyester 
       add constraint FKhn2hnmiq6fur1dv22f2ysuo88 
       foreign key (color_id) 
       references tb_color;

    alter table tb_polyethylene 
       add constraint FKqrh39p9gxpwvf8hobrcynrfv8 
       foreign key (color_id) 
       references tb_color;

    alter table tb_sheet 
       add constraint FK446e3drog00kivo6g058pixdf 
       foreign key (color_id) 
       references tb_color;

    alter table tb_sheet 
       add constraint FKmpj6ufg0hl5ckwyjjb4e0jkqf 
       foreign key (material_id) 
       references tb_material;

    alter table tb_used_back_sheet 
       add constraint FKnv43m1vw6ih1tvh4c821i3xbd 
       foreign key (back_id) 
       references tb_back;

    alter table tb_used_back_sheet 
       add constraint FKcud7gvt35ufjcnsjov9tvp5w9 
       foreign key (sheet_id) 
       references tb_sheet;

    alter table tb_used_corner_bracket 
       add constraint FK5kiudeteld1e1ehgl1yqrxpvx 
       foreign key (corner_bracket_id) 
       references tb_corner_bracket;

    alter table tb_used_corner_bracket 
       add constraint FKi13yfc5jqovrmb4yrian7kpm5 
       foreign key (ghost_id) 
       references tb_ghost;

    alter table tb_used_drawer_pull 
       add constraint FK6k9k1tf57ny1xcsdo5orli53e 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_used_drawer_pull 
       add constraint FK2o56ltop9ojxb37km41men4kj 
       foreign key (drawer_pull_id) 
       references tb_item;

    alter table tb_used_edge_banding 
       add constraint FKa8ru4l8kcr85dsxkdll9v7qpp 
       foreign key (edge_banding_id) 
       references tb_edge_banding;

    alter table tb_used_edge_banding 
       add constraint FKhhbuypevladdsmi08lo8u1mtd 
       foreign key (son_id) 
       references tb_item;

    alter table tb_used_glass 
       add constraint FKiifx5ou6rdohvwru7y6yokg6t 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_used_glass 
       add constraint FKhiw98ds8ywtyh2hgfynn8rt99 
       foreign key (glass_id) 
       references tb_item;

    alter table tb_used_glue 
       add constraint FKeagumk2sr8pybqc920mk1sx74 
       foreign key (glue_id) 
       references tb_glue;

    alter table tb_used_glue 
       add constraint FKlqqajnxrfcvi0jaqxwj9d93nv 
       foreign key (son_id) 
       references tb_item;

    alter table tb_used_molding 
       add constraint FK55yyiwn6q5g77e1y10hd6liok 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_used_molding 
       add constraint FKlcwxk8v0n0hch5qpp93vk2qqx 
       foreign key (molding_id) 
       references tb_item;

    alter table tb_used_nonwoven_fabric 
       add constraint FKqrhkdh0h22eh8b8cb1apgoqdh 
       foreign key (ghost_id) 
       references tb_ghost;

    alter table tb_used_nonwoven_fabric 
       add constraint FKruhvt8xf120u6p5qt0bdmcyst 
       foreign key (nonwoven_fabric_id) 
       references tb_nonwoven_fabric;

    alter table tb_used_painting 
       add constraint FKmu2dh2n7irwue2443oop87bap 
       foreign key (painting_id) 
       references tb_painting;

    alter table tb_used_painting 
       add constraint FKrb9ux3b7em1b2i7bu4th4p23a 
       foreign key (painting_son_id) 
       references tb_item;

    alter table tb_used_painting_border_background 
       add constraint FKj2gklvwfqe5d4wlufxxwcw0hi 
       foreign key (painting_border_background_id) 
       references tb_painting_border_background;

    alter table tb_used_painting_border_background 
       add constraint FKju3cv04eewutfyof138utwd6u 
       foreign key (painting_son_id) 
       references tb_item;

    alter table tb_used_plastic 
       add constraint FKoaixefhyxndr1i0fyouycw9tf 
       foreign key (ghost_id) 
       references tb_ghost;

    alter table tb_used_plastic 
       add constraint FK3wtpps817dv7fjfc7t8mgr8sc 
       foreign key (plastic_id) 
       references tb_plastic;

    alter table tb_used_polyester 
       add constraint FKqnl18l36otjxo0lwnipd9d00p 
       foreign key (painting_son_id) 
       references tb_item;

    alter table tb_used_polyester 
       add constraint FKjxlp7kpvumgvf76udspivh02e 
       foreign key (polyester_id) 
       references tb_polyester;

    alter table tb_used_polyethylene 
       add constraint FK3ukmiwt6xg1gxg961dau51x34 
       foreign key (ghost_id) 
       references tb_ghost;

    alter table tb_used_polyethylene 
       add constraint FKcm1depktpykfs41esnwwtc6pk 
       foreign key (polyethylene_id) 
       references tb_polyethylene;

    alter table tb_used_screw 
       add constraint FKrecg6qvlf1k7gumibkr2hedmy 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_used_screw 
       add constraint FKjo8rmi13md4999v2wnjow6p2s 
       foreign key (screw_id) 
       references tb_item;

    alter table tb_used_sheet 
       add constraint FKd60bilav2sm3fxyiotg0l4p9r 
       foreign key (sheet_id) 
       references tb_sheet;

    alter table tb_used_sheet 
       add constraint FKo68uj0htmon0uvq8ib61yopc5 
       foreign key (son_id) 
       references tb_item;

    alter table tb_used_try_square 
       add constraint FKouf6l8kvwmiv15xlrb8ip2den 
       foreign key (aluminium_son_id) 
       references tb_item;

    alter table tb_used_try_square 
       add constraint FKliswxkfciky7w88x81g5quky2 
       foreign key (try_square_id) 
       references tb_item;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
	   
INSERT INTO tb_user (name, email, password, img_Url, status) VALUES ('Alex', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/47.jpg', 'ACTIVE');
INSERT INTO tb_user (name, email, password, img_Url, status) VALUES ('Maria', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://i.pinimg.com/originals/76/ef/b7/76efb7c94755748d695d3d46cf11d08d.jpg', 'ACTIVE');
INSERT INTO tb_user (name, email, password, img_Url, status) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'https://xsgames.co/randomusers/assets/avatars/male/62.jpg', 'ACTIVE');
INSERT INTO tb_role (authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_color (code, name, status) VALUES (307, 'MINERALE', 'ACTIVE');
INSERT INTO tb_color (code, name, status) VALUES (302, 'PRISMA', 'ACTIVE');
INSERT INTO tb_color (code, name, status) VALUES (308, 'STONE', 'ACTIVE');
INSERT INTO tb_material (name, status) VALUES ('MDP', 'ACTIVE');
INSERT INTO tb_material (name, status) VALUES ('MDF', 'ACTIVE');
INSERT INTO tb_sheet (code, description, thickness, implementation, faces, lost_percentage, color_id, material_id, status) VALUES (1022602, 'MDP BP 18MM - MINERALE/CZ COBALTO 2F', 18.0, null, 2, 13, 307, 1, 'ACTIVE');
INSERT INTO tb_sheet (code, description, thickness, implementation, faces, lost_percentage, color_id, material_id, status) VALUES (1022610, 'MDP BP 18MM - PRISMA 2F', 18.0, null, 2, 13, 302, 1, 'ACTIVE');
INSERT INTO tb_sheet (code, description, thickness, implementation, faces, lost_percentage, color_id, material_id, status) VALUES (1022618, 'MDP BP 18MM - STONE/CHUMBO 2F', 18.0, null, 2, 13, 308, 1, 'ACTIVE');
INSERT INTO tb_sheet (code, description, thickness, implementation, faces, lost_percentage, color_id, material_id, status) VALUES (10, 'MDF BP 18 MM 2F', 18, null, 2, 10 , null, 2, 'ACTIVE');
INSERT INTO tb_sheet (code, description, thickness, implementation, faces, lost_percentage, color_id, material_id, status) VALUES (11, 'MDF BP 18 MM 1F', 18, null, 1, 10 , null, 2, 'ACTIVE');
INSERT INTO tb_edge_banding (code, description, height, thickness, family, implementation, lost_percentage, color_id, status) VALUES (1022604, 'FITA BORDA PS 2107 - MINERALE/CZ COBALTO', 21, 7, '11FITABO', null, 8.6, 307, 'ACTIVE');
INSERT INTO tb_edge_banding (code, description, height, thickness, family, implementation, lost_percentage, color_id, status) VALUES (1022613, 'FITA BORDA PS 2107 - PRISMA', 21, 7, '11FITABO', null, 8.6, 302, 'ACTIVE');
INSERT INTO tb_edge_banding (code, description, height, thickness, family, implementation, lost_percentage, color_id, status) VALUES (1022620, 'FITA BORDA PS 2107 - STONE/CHUMBO', 21, 7, '11FITABO', null, 8.6, 308, 'ACTIVE');
INSERT INTO tb_glue (code, description, grammage, lost_percentage, status) VALUES (1025359,	'COLA PUR CQ 645', 0.09, 12, 'ACTIVE');
INSERT INTO tb_corner_bracket (code, description, status) VALUES (111111, 'CORNER BRACKET 1', 'ACTIVE');
INSERT INTO tb_nonwoven_fabric (code, description, lost_percentage, status) VALUES (222222, 'NONWOVEN FABRIC 1', 10.0, 'ACTIVE');
INSERT INTO tb_plastic (code, description, grammage, lost_percentage, status) VALUES (333333, 'PLASTIC 1', 0.5, 10, 'ACTIVE');
INSERT INTO tb_polyethylene (code, description, lost_percentage, status) VALUES (444444, 'POLYETHYLENE 1', 10, 'ACTIVE');
INSERT INTO tb_painting_type (description, status) VALUES ('Satin', 'ACTIVE');
INSERT INTO tb_painting_type (description, status) VALUES ('High Shine', 'ACTIVE');
INSERT INTO tb_painting_type (description, status) VALUES ('Satin Glass', 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (201, 'MINERALE', 10, 1, 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (202, 'PRISMA', 10, 1, 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (203, 'STONE', 10, 1, 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (204, 'MINERALE', 10, 2, 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (205, 'PRISMA', 10, 2, 'ACTIVE');
INSERT INTO tb_painting (code, description, lost_percentage, painting_type_id, status) VALUES (206, 'STONE', 10, 2, 'ACTIVE');
INSERT INTO tb_painting_border_background (code, description, lost_percentage, status) VALUES (30, 'Standard Painting Border', 10, 'ACTIVE');
INSERT INTO tb_polyester (code, description, lost_percentage, status) VALUES (40, 'Standard Polyester', 10, 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (1019262, 'ACAB FTE GAV ALUM TRANSLUCIDO 810 MM', 810, 16, 16, 'Attachment', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (70002299, 'ACESSÓRIO GAVETA ALUM H-90 P-500', 500, 90, 18, 'Attachment', 'ACTIVE');
INSERT INTO tb_aluminium_type (name, less_quantity, status) VALUES ('MOCCA', 0.5, 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (888, 'PUXADOR ALUMINIO', 192, 35, 5, 'DrawerPull', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, color_id, dtype, status) VALUES (10108000, 'VIDRO TEMPERADO MINERALE', 2205, 581, 18, 307, 'Glass', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, color_id, dtype, status) VALUES (10108001, 'VIDRO TEMPERADO PRISMA', 2205, 581, 18, 302, 'Glass', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (155687, 'PERFIL BAGUETE 123', null, null, null, 'Molding', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (158963, 'PARAFUSO 18 MM BRANCO', null, null, null, 'Screw', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (158964, 'PARAFUSO 18 MM PRETO', null, null, null, 'Screw', 'ACTIVE');
INSERT INTO tb_item (code, description, measure1, measure2, measure3, dtype, status) VALUES (1693258, 'TRY SQUARE 3456', null, null, null, 'TrySquare', 'ACTIVE');
INSERT INTO tb_machine_group (name, status) VALUES ('CNCs', 'ACTIVE');
